#!/bin/bash

# author settings
AUTHOR="Björn Hempel"
EMAIL="bjoern@hempel.li"

# declare parameter list array
PARAMETERS=()

# some default vars
SHOW_ONLY_APP_NAME=false

# read arguments
# help:
# help: A project analyser (%version%) by %author% <%email%>.
# help:
# help: Usage: %scriptname% [options...] [<path>]
while [[ $# > 0 ]]; do
    case "$1" in
        # help:  -h,    --help                    Shows this help.
        -h|--help)
            version=$(getRepositoryVersion "$pathRoot" true)
            cat "$BASH_SOURCE" | grep "# help:" | grep -v 'cat parameter' | sed 's/[ ]*# help:[ ]\?//g' | \
                sed "s~%scriptname%~$scriptname~g" | \
                sed "s~%version%~$version~g" | \
                sed "s~%author%~$AUTHOR~g" | \
                sed "s~%email%~$EMAIL~g"
            exit 0
            ;;

        # help:  -v,    --version                 Shows the version number.
        -v|--version)
            version=$(getRepositoryVersion "$pathRoot")
            echo "$version"
            exit 0
            ;;

        # help:
        # help:         --show-only-app-name      Shows only the app name.
        --show-only-app-name)
            SHOW_ONLY_APP_NAME=true
            ;;

        # help:
        #
        # collect all unknown parameters
        #
        *)
            PARAMETERS+=("$1")
            ;;
    esac
    shift
done

